-- seed CET6 essay prompts
-- source: CET-6 writing prompts (2015-06 to 2025-06)
-- normalized for current schema: essay_prompt.task = 'task1'

-- 2025年6月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2025年6月第1套', '求职准备', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "As requirements for job applications are getting increasingly higher, college students ought to be better prepared for their future career." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words. You should copy the sentence given in quotes at the beginning of your essay.', 2025, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2025年6月第1套', 1),
(3, '2025年6月第2套', '社交媒体的合理使用', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "As social media is used more and more extensively, there is a growing awareness of the importance of using it properly and responsibly." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words. You should copy the sentence given in quotes at the beginning of your essay.', 2025, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2025年6月第2套', 1),
(3, '2025年6月第3套', 'AI与人类创造力', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "With the increasing application of AI technology, there is a growing concern that it may negatively impact human creativity." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words. You should copy the sentence given in quotes at the beginning of your essay.', 2025, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2025年6月第3套', 1);

-- 2024年12月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2024年12月第1套', '设定目标与持之以恒', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "To increase the likelihood of success, one should set realistic goals and work persistently towards them." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words. You should copy the sentence given in quotes at the beginning of your essay.', 2024, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2024年12月第1套', 1),
(3, '2024年12月第2套', '自律与个人成长', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "Nowadays, more and more students have realized the importance of self-discipline in their personal growth." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words. You should copy the sentence given in quotes at the beginning of your essay.', 2024, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2024年12月第2套', 1),
(3, '2024年12月第3套', '大学探索与人生路径', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "College provides a great opportunity for students to explore various possibilities and find the right path for themselves." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words. You should copy the sentence given in quotes at the beginning of your essay.', 2024, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2024年12月第3套', 1);

-- 2024年6月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2024年6月第1套', '数字素养的重要性', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "there is a growing awareness of the importance of digital literacy and skills in today''s world." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words.', 2024, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2024年6月第1套', 1),
(3, '2024年6月第2套', '社会实践与学术学习', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "Nowadays more and more college students have come to realize social practice and academic learning are equally important." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words.', 2024, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2024年6月第2套', 1),
(3, '2024年6月第3套', '自主学习能力', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "Nowadays, cultivating independent learning ability is becoming increasingly crucial for personal development." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words.', 2024, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2024年6月第3套', 1);

-- 2023年12月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2023年12月第1套', '扎实基础的重要性', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "As is known to all, gaining a sound knowledge of the basics is of vital importance for students to master an academic subject." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words.', 2023, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2023年12月第1套', 1),
(3, '2023年12月第2套', '给孩子更多自由探索', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "Nowadays parents are increasingly aware that allowing kids more freedom to explore and learn on their own helps foster their independence and boost their confidence." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words.', 2023, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2023年12月第2套', 1),
(3, '2023年12月第3套', '老年人的社会贡献', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "With their valuable skills and experience, elderly people can continue to make significant contributions to society." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words.', 2023, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2023年12月第3套', 1);

-- 2023年6月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2023年6月第1套', '心理健康与身体健康', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "Today there is a growing awareness that mental well-being needs to be given as much attention as physical health." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words.', 2023, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2023年6月第1套', 1),
(3, '2023年6月第2套', '友好讨论解决分歧', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "When faced with differing opinions, we should try to reach agreement through friendly discussion and reasonable argument." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words.', 2023, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2023年6月第2套', 1),
(3, '2023年6月第3套', '学会学习', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "It is widely accepted that an important goal of education is to help students learn how to learn." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words.', 2023, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2023年6月第3套', 1);

-- 2023年3月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2023年3月第1套', '外貌焦虑', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "People are now increasingly aware of the danger of ''appearance anxiety'' or being obsessed with one''s looks." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words.', 2023, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2023年3月第1套', 1),
(3, '2023年3月第2套', '选择过多的困难', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "People are now increasingly aware of the challenges in making a decision when faced with too many choices." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words.', 2023, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2023年3月第2套', 1),
(3, '2023年3月第3套', '老年人的数字鸿沟', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "People are now increasingly aware of the ''digital gap'' or challenges the elderly face in a digital world." You can make comments, give explanations, or cite examples to develop your essay. You should write at least 150 words but no more than 200 words.', 2023, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2023年3月第3套', 1);

-- 2022年12月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2022年12月第1套', '信息技术与多元学习', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "With the application of information technology in education, college students can now learn in more diverse and efficient ways." You can make statements, give reasons, or cite examples to develop your essay. You should write at least 150 words but no more than 200 words.', 2022, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2022年12月第1套', 1),
(3, '2022年12月第2套', '批判性思维与理性选择', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "In an era of information explosion, it is vitally important to develop the ability to think critically and make rational choices." You can make statements, give reasons, or cite examples to develop your essay. You should write at least 150 words but no more than 200 words.', 2022, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2022年12月第2套', 1),
(3, '2022年12月第3套', '培养团队精神', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "Today increasing importance is being attached to cultivating college students'' team spirit." You can make statements, give reasons, or cite examples to develop your essay. You should write at least 150 words but no more than 200 words.', 2022, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2022年12月第3套', 1);

-- 2022年9月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2022年9月第1套', '数字技能的重要性', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "Nowadays more and more students are becoming increasingly aware of the importance of developing digital skills." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words.', 2022, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2022年9月第1套', 1),
(3, '2022年9月第2套', '现实社交的乐趣', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "Today more and more people begin to realize the pleasures and joys of real-world social interaction." You can make comments, cite examples or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words.', 2022, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2022年9月第2套', 1),
(3, '2022年9月第3套', '互信与合作', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "It is now widely accepted that mutual trust and openness is the key to promoting cooperation." You can make comments, cite examples, or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words.', 2022, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2022年9月第3套', 1);

-- 2022年6月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2022年6月第1套', '环保生活方式', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "Nowadays more and more people choose to live an environmentally friendly lifestyle." You can make comments, cite examples, or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words.', 2022, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2022年6月第1套', 1),
(3, '2022年6月第2套', '持续学习新技能', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "Nowadays more and more people keep learning new skills to adapt to a fast-changing world." You can make comments, cite examples, or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words.', 2022, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2022年6月第2套', 1),
(3, '2022年6月第3套', '乐于助人', 'For this part, you are allowed 30 minutes to write an essay that begins with the sentence "Nowadays more and more people take delight in offering help to the needy." You can make comments, cite examples, or use your personal experiences to develop your essay. You should write at least 150 words but no more than 200 words.', 2022, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2022年6月第3套', 1);

-- 2021年12月 (现象评论+建议，有material_text)
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2021年12月第1套', '青年人与网络虚假信息', 'For this part, you are allowed 30 minutes to write an essay related to the short passage given below. In your essay, you are to comment on the phenomenon described in the passage and suggest measures to address the issue. You should write at least 150 words but no more than 200 words.', 2021, NULL, NULL, 'Young people spend a lot of time on the Internet. However, they are sometimes unable to recognize false information on the Internet, judge the reliability of online information sources, or tell real news stories from fake ones.', 'task1', 150, 200, 106, 'CET-6 2021年12月第1套', 1),
(3, '2021年12月第2套', '青少年追星现象', 'For this part, you are allowed 30 minutes to write an essay related to the short passage given below. In your essay, you are to comment on the phenomenon described in the passage and suggest measures to address the issue. You should write at least 150 words but no more than 200 words.', 2021, NULL, NULL, 'Nowadays star chasing is prevalent among many teenagers. They take pop stars as their idols, imitating their way of talking, following their style of dressing, and seeking every chance to meet them in person at great expenses.', 'task1', 150, 200, 106, 'CET-6 2021年12月第2套', 1),
(3, '2021年12月第3套', '中国家长的过度保护', 'For this part, you are allowed 30 minutes to write an essay related to the short passage given below. In your essay, you are to comment on the phenomenon described in the passage and suggest measures to address the issue. You should write at least 150 words but no more than 200 words.', 2021, NULL, NULL, 'Some parents in China are overprotective of their children. They plan everything for their children, make all the decisions for them, and do not allow them to explore on their own in case they make mistakes or get hurt.', 'task1', 150, 200, 106, 'CET-6 2021年12月第3套', 1);

-- 2021年6月 (图表描述+评论，有image_description)
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2021年6月第1套', '中国城镇化成就', 'For this part, you are allowed 30 minutes to write an essay based on the graph below. You should start your essay with a brief description of the graph and comment on China''s achievements in urbanization. You should write at least 150 words but no more than 200 words.', 2021, NULL, '折线图+柱状图：Degree of urbanization in China from 1980 to 2019。纵轴为Share of urban population（城镇人口占比），横轴为年份。数据点：1980年19.39%、1985年23.71%、1990年26.41%、1995年29.04%、2000年36.22%、2005年42.99%、2010年49.95%、2011年51.27%、2012年53.73%、2014年56.1%、2016年57.35%、2018年59.58%、2019年60.6%。整体呈持续上升趋势，从约19%增长至超过60%。', NULL, 'task1', 150, 200, 106, 'CET-6 2021年6月第1套', 1),
(3, '2021年6月第2套', '中国高等教育成就', 'For this part, you are allowed 30 minutes to write an essay based on the chart below. You should start your essay with a brief description of the chart and comment on China''s achievements in higher education. You should write at least 150 words but no more than 200 words.', 2021, NULL, '柱状图+折线图：Gross enrolment ratio in higher education in China (1990-2019)。数据来源：Ministry of Education, CGTN。关键数据：1990年3.4%、1995年6.86%、2000年13.3%、2005年22%、2010年30%、2015年40%、2019年51.6%。整体呈持续快速上升趋势，从3.4%增长至51.6%，跨越了高等教育大众化（15%）和普及化（50%）两个门槛。', NULL, 'task1', 150, 200, 106, 'CET-6 2021年6月第2套', 1),
(3, '2021年6月第3套', '中国脱贫攻坚成就', 'For this part, you are allowed 30 minutes to write an essay based on the graph below. You should start your essay with a brief description of the graph and comment on China''s achievements in poverty alleviation. You should write at least 150 words but no more than 200 words.', 2021, NULL, '柱状图+折线图：Rural population in poverty。左纵轴为农村贫困人口（百万人），右纵轴为贫困发生率（占农村人口百分比）。数据来源：China''s National Bureau of Statistics。数据区间2012-2020年，贫困人口从2012年约9899万人持续下降至2020年归零；贫困发生率从2012年约10.2%持续下降至2020年0%。展示了中国脱贫攻坚的显著成就。', NULL, 'task1', 150, 200, 106, 'CET-6 2021年6月第3套', 1);

-- 2020年12月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2020年12月第1套', '鼓励学生培养创造力', 'For this part, you are allowed 30 minutes to write an essay on why students should be encouraged to develop creativity. You should write at least 150 words but no more than 200 words.', 2020, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2020年12月第1套', 1),
(3, '2020年12月第2套', '鼓励学生培养沟通能力', 'For this part, you are allowed 30 minutes to write an essay on why students should be encouraged to develop effective communication skills. You should write at least 150 words but no more than 200 words.', 2020, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2020年12月第2套', 1),
(3, '2020年12月第3套', '鼓励学生培养应对挑战的能力', 'For this part, you are allowed 30 minutes to write an essay on why students should be encouraged to develop the ability to meet challenges. You should write at least 150 words but no more than 200 words.', 2020, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2020年12月第3套', 1);

-- 2020年9月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2020年9月第1套', '心灵之美', 'For this part, you are allowed 30 minutes to write an essay on the saying "Beauty of the soul is the essential beauty." You should write at least 150 words but no more than 200 words.', 2020, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2020年9月第1套', 1),
(3, '2020年9月第2套', '值得做就值得做好', 'For this part, you are allowed 30 minutes to write an essay on the saying "What is worth doing is worth doing well." You should write at least 150 words but no more than 200 words.', 2020, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2020年9月第2套', 1),
(3, '2020年9月第3套', '精神财富', 'For this part, you are allowed 30 minutes to write an essay on the saying "Wealth of the mind is the only true wealth." You should write at least 150 words but no more than 200 words.', 2020, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2020年9月第3套', 1);

-- 2020年7月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2020年7月第1套', '做好今天是对明天最好的准备', 'For this part, you are allowed 30 minutes to write an essay on the saying "The best preparation for tomorrow is doing your best today." You should write at least 150 words but no more than 200 words.', 2020, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2020年7月第1套', 1);

-- 2019年12月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2019年12月第1套', '社会责任感', 'For this part, you are allowed 30 minutes to write an essay on the importance of having a sense of social responsibility. You should write at least 150 words but no more than 200 words.', 2019, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2019年12月第1套', 1),
(3, '2019年12月第2套', '家庭责任感', 'For this part, you are allowed 30 minutes to write an essay on the importance of having a sense of family responsibility. You should write at least 150 words but no more than 200 words.', 2019, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2019年12月第2套', 1),
(3, '2019年12月第3套', '社区责任感', 'For this part, you are allowed 30 minutes to write an essay on the importance of having a sense of community responsibility. You should write at least 150 words but no more than 200 words.', 2019, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2019年12月第3套', 1);

-- 2019年6月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2019年6月第1套', '职场团队精神与沟通', 'For this part, you are allowed 30 minutes to write an essay on the importance of team spirit and communication in the workplace. You should write at least 150 words but no more than 200 words.', 2019, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2019年6月第1套', 1),
(3, '2019年6月第2套', '人际关系中的理解与尊重', 'For this part, you are allowed 30 minutes to write an essay on the importance of mutual understanding and respect in interpersonal relationships. You should write at least 150 words but no more than 200 words.', 2019, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2019年6月第2套', 1),
(3, '2019年6月第3套', '学习的动力与方法', 'For this part, you are allowed 30 minutes to write an essay on the importance of motivation and methods in learning. You should write at least 150 words but no more than 200 words.', 2019, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2019年6月第3套', 1);

-- 2018年12月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2018年12月第1套', '平衡工作与休闲', 'For this part, you are allowed 30 minutes to write an essay on how to balance work and leisure. You should write at least 150 words but no more than 200 words.', 2018, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2018年12月第1套', 1),
(3, '2018年12月第2套', '平衡工作与个人兴趣', 'For this part, you are allowed 30 minutes to write an essay on how to balance job responsibilities and personal interests. You should write at least 150 words but no more than 200 words.', 2018, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2018年12月第2套', 1),
(3, '2018年12月第3套', '平衡学业与课外活动', 'For this part, you are allowed 30 minutes to write an essay on how to balance academic study and extracurricular activities. You should write at least 150 words but no more than 200 words.', 2018, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2018年12月第3套', 1);

-- 2018年6月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2018年6月第1套', '雇主与员工之间的信任', 'For this part, you are allowed 30 minutes to write an essay on the importance of building trust between employers and employees. You can cite examples to illustrate your views. You should write at least 150 words but no more than 200 words.', 2018, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2018年6月第1套', 1),
(3, '2018年6月第2套', '师生之间的信任', 'For this part, you are allowed 30 minutes to write an essay on the importance of building trust between teachers and students. You can cite examples to illustrate your views. You should write at least 150 words but no more than 200 words.', 2018, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2018年6月第2套', 1),
(3, '2018年6月第3套', '企业与消费者之间的信任', 'For this part, you are allowed 30 minutes to write an essay on the importance of building trust between businesses and consumers. You can cite examples to illustrate your views. You should write at least 150 words but no more than 200 words.', 2018, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2018年6月第3套', 1);

-- 2017年12月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2017年12月第1套', '尊重他人', 'For this part, you are allowed 30 minutes to write an essay commenting on the saying "Respect others, and you will be respected." You can cite examples to illustrate your views. You should write at least 150 words but no more than 200 words.', 2017, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2017年12月第1套', 1),
(3, '2017年12月第2套', '理解他人', 'For this part, you are allowed 30 minutes to write an essay commenting on the saying "Seek to understand others, and you will be understood." You can cite examples to illustrate your views. You should write at least 150 words but no more than 200 words.', 2017, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2017年12月第2套', 1),
(3, '2017年12月第3套', '帮助他人', 'For this part, you are allowed 30 minutes to write an essay commenting on the saying "Help others, and you will be helped when you are in need." You can cite examples to illustrate your views. You should write at least 150 words but no more than 200 words.', 2017, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2017年12月第3套', 1);

-- 2017年6月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2017年6月第1套', '理科还是文科', 'Suppose you are asked to give advice on whether to major in science or humanities at college, write an essay to state your opinion. You are required to write at least 150 words but no more than 200 words.', 2017, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2017年6月第1套', 1),
(3, '2017年6月第2套', '职业院校还是大学', 'For this part, you are allowed 30 minutes to write an essay on whether to attend a vocational college or a university. You should write at least 150 words but no more than 200 words.', 2017, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2017年6月第2套', 1),
(3, '2017年6月第3套', '国内还是国外上大学', 'Suppose you are asked to give advice on whether to attend college at home or abroad, write an essay to state your opinion. You are required to write at least 150 words but no more than 200 words.', 2017, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2017年6月第3套', 1);

-- 2016年12月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2016年12月第1套', '发明的重要性', 'For this part, you are allowed 30 minutes to write a short essay on invention. Your essay should include the importance of invention and measures to be taken to encourage invention. You are required to write at least 150 words but no more than 200 words.', 2016, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2016年12月第1套', 1),
(3, '2016年12月第2套', '创新的重要性', 'For this part, you are allowed 30 minutes to write a short essay on innovation. Your essay should include the importance of innovation and measures to be taken to encourage innovation. You are required to write at least 150 words but no more than 200 words.', 2016, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2016年12月第2套', 1),
(3, '2016年12月第3套', '创造的重要性', 'For this part, you are allowed 30 minutes to write a short essay on creation. Your essay should include the importance of creation and measures to be taken to encourage creation. You are required to write at least 150 words but no more than 200 words.', 2016, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2016年12月第3套', 1);

-- 2016年6月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2016年6月第1套', '虚拟世界生活', 'For this part, you are allowed 30 minutes to write a short essay on living in the virtual world. Try to imagine what will happen when people spend more and more time in the virtual world instead of interacting in the real world. You are required to write at least 150 words but no more than 200 words.', 2016, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2016年6月第1套', 1),
(3, '2016年6月第2套', '机器人的使用', 'For this part, you are allowed 30 minutes to write a short essay on the use of robots. Try to imagine what will happen when more and more robots take the place of human beings in industry as well as people''s daily lives. You are required to write at least 150 words but no more than 200 words.', 2016, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2016年6月第2套', 1),
(3, '2016年6月第3套', '在线学习', 'For this part, you are allowed 30 minutes to write a short essay on e-learning. Try to imagine what will happen when more and more people study online instead of attending school. You are required to write at least 150 words but no more than 200 words.', 2016, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2016年6月第3套', 1);

-- 2015年12月 (看图写作，有image_description)
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2015年12月第1套', '网络虚假信息的危害', 'For this part, you are allowed 30 minutes to write a short essay based on the picture below. You should focus on the harm caused by misleading information online. You are required to write at least 150 words but no more than 200 words.', 2015, NULL, '漫画：一个人坐在电脑前浏览网页，旁边站着一个人端着咖啡杯。画面表现的是人们在网上接触到大量虚假和误导性信息的场景。', NULL, 'task1', 150, 200, 106, 'CET-6 2015年12月第1套', 1),
(3, '2015年12月第2套', '社交网站对阅读的影响', 'For this part, you are allowed 30 minutes to write a short essay based on the picture below. You should focus on the impact of social networking websites on reading. You are required to write at least 150 words but no more than 200 words.', 2015, NULL, '漫画：一个人坐在桌前使用电脑，配文："I love reading. I read about 3 hours a day. My favorite book is Facebook." 注释说明Facebook是一个社交网站的名称。画面讽刺地表达了人们将浏览社交网站等同于阅读的现象。', NULL, 'task1', 150, 200, 106, 'CET-6 2015年12月第2套', 1),
(3, '2015年12月第3套', '信息技术时代获取有用信息的困难', 'For this part, you are allowed 30 minutes to write a short essay based on the picture below. You should focus on the difficulty in acquiring useful information in spite of advanced information technology. You are required to write at least 150 words but no more than 200 words.', 2015, NULL, '漫画：几个人围坐在会议桌旁，桌上有电脑等设备，配文："We have lots of information technology. We just don''t have much useful information." 画面表达了尽管信息技术高度发达，人们仍然难以获取真正有用信息的悖论。', NULL, 'task1', 150, 200, 106, 'CET-6 2015年12月第3套', 1);

-- 2015年6月
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, word_count_min, word_count_max, max_score, source, is_active) VALUES
(3, '2015年6月第1套', '知识与实践', 'For this part, you are allowed 30 minutes to write an essay commenting on the saying "Knowledge is a treasure, but practice is the key to it." You can cite one example or two to illustrate your point of view. You should write at least 150 words but no more than 200 words.', 2015, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2015年6月第1套', 1),
(3, '2015年6月第2套', '好奇心的力量', 'For this part, you are allowed 30 minutes to write an essay commenting on Albert Einstein''s remark "I have no special talents. I am only passionately curious." You can give an example or two to illustrate your point of view. You should write at least 150 words but no more than 200 words.', 2015, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2015年6月第2套', 1),
(3, '2015年6月第3套', '把小事做好', 'For this part, you are allowed 30 minutes to write an essay commenting on the saying "If you cannot do great things, do small things in a great way." You can cite examples to illustrate your point of view. You should write at least 150 words but no more than 200 words.', 2015, NULL, NULL, NULL, 'task1', 150, 200, 106, 'CET-6 2015年6月第3套', 1);


