CREATE TABLE IF NOT EXISTS learning_extraction_run (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    run_uid VARCHAR(96) NOT NULL,
    user_id BIGINT NOT NULL,
    conversation_uid VARCHAR(64) NOT NULL,
    message_uid VARCHAR(64) NOT NULL,
    extractor_type VARCHAR(32) NOT NULL COMMENT 'local | deepseek',
    status VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'pending | processing | completed | failed',
    model VARCHAR(128) NULL,
    input_token_count BIGINT NULL,
    output_token_count BIGINT NULL,
    result_json JSON NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_learning_extraction_run_uid (run_uid),
    UNIQUE KEY uk_learning_extraction_run_message_extractor (message_uid, extractor_type),
    KEY idx_learning_extraction_run_user_time (user_id, created_at),
    KEY idx_learning_extraction_run_message (message_uid),
    KEY idx_learning_extraction_run_extractor_status (extractor_type, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='learning capture extraction runs';

CREATE TABLE IF NOT EXISTS learning_raw_candidate (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    candidate_uid VARCHAR(96) NOT NULL,
    user_id BIGINT NOT NULL,
    conversation_uid VARCHAR(64) NOT NULL,
    message_uid VARCHAR(64) NOT NULL,
    source_role VARCHAR(16) NOT NULL,
    candidate_type VARCHAR(32) NOT NULL COMMENT 'word | phrase | sentence | sentence_pattern',
    text VARCHAR(1000) NOT NULL,
    normalized_text VARCHAR(255) NOT NULL,
    extractor_type VARCHAR(32) NOT NULL COMMENT 'local | deepseek',
    extraction_run_uid VARCHAR(96) NOT NULL,
    source_excerpt TEXT NULL,
    source_heading VARCHAR(160) NULL,
    local_signals_json JSON NULL,
    local_feature_json JSON NULL,
    model_confidence DECIMAL(5,4) NULL,
    comparison_status VARCHAR(32) NULL COMMENT 'overlap | local_only | deepseek_only | type_conflict',
    local_prefilter_score DECIMAL(6,2) NULL,
    embedding_score DECIMAL(6,2) NULL,
    judge_score DECIMAL(6,2) NULL,
    final_candidate_score DECIMAL(6,2) NULL,
    occurrence_count INT NOT NULL DEFAULT 1,
    first_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_learning_raw_candidate_uid (candidate_uid),
    UNIQUE KEY uk_learning_raw_candidate_dedupe (user_id, candidate_type, normalized_text, extractor_type),
    KEY idx_learning_raw_candidate_message (message_uid),
    KEY idx_learning_raw_candidate_extractor (extractor_type),
    KEY idx_learning_raw_candidate_comparison (comparison_status),
    KEY idx_learning_raw_candidate_last_seen (last_seen_at),
    KEY idx_learning_raw_candidate_user_type_seen (user_id, candidate_type, last_seen_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='raw learning candidates from local and model extractors';

CREATE TABLE IF NOT EXISTS learning_evidence (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    evidence_uid VARCHAR(96) NOT NULL,
    candidate_uid VARCHAR(96) NOT NULL,
    user_id BIGINT NOT NULL,
    evidence_type VARCHAR(32) NOT NULL COMMENT 'user_focus | key_expression | alternative_expression | sentence_pattern | practice_sentence',
    text VARCHAR(1000) NOT NULL,
    score DECIMAL(6,2) NOT NULL DEFAULT 0,
    signals_json JSON NULL,
    model_judgement_json JSON NULL,
    extractor_sources_json JSON NULL,
    comparison_status VARCHAR(32) NULL,
    source_message_ids_json JSON NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'pending | consumed | ignored',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_learning_evidence_uid (evidence_uid),
    UNIQUE KEY uk_learning_evidence_candidate (candidate_uid),
    KEY idx_learning_evidence_user_status_score (user_id, status, score),
    KEY idx_learning_evidence_candidate (candidate_uid),
    KEY idx_learning_evidence_comparison (comparison_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='selected learning evidence for downstream consumer model';
