-- =============================================================================
-- 考研英语作文真题种子数据（2005-2025）
-- 英语一：2005-2025（小作文 task1 + 大作文 task2）
-- 英语二：2010-2025（小作文 task1 + 大作文 task2）
-- stage_id = 4 (postgrad)
-- 新增 image_description 列：task2 条目存放 "{caption}。{description}"
-- =============================================================================

-- 英语一 小作文（task1）
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, source, is_active) VALUES
    (4, '2005-postgrad-en1', '考研英语一小作文 2005', 'Two months ago you got a job as an editor for the magazine Designs & Fashions. But now you find that the work is not what you expected. You decide to quit. Write a letter to your boss, Mr. Wang, telling him your decision, stating your reason(s), and making an apology.', 2005, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2006-postgrad-en1', '考研英语一小作文 2006', 'You want to contribute to Project Hope by offering financial aid to a child in a remote area. Write a letter to the department concerned, asking them to help find a candidate. You should specify what kind of child you want to help and how you will carry out your plan.', 2006, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2007-postgrad-en1', '考研英语一小作文 2007', 'Write a letter to your university library, making suggestions for improving its service.', 2007, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2008-postgrad-en1', '考研英语一小作文 2008', 'You have just come back from Canada and found a music CD in your luggage that you forgot to return to Bob, your landlord there. Write him a letter to: 1) make an apology, and 2) suggest a solution.', 2008, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2009-postgrad-en1', '考研英语一小作文 2009', 'Restrictions on the use of plastic bags have not been so successful in some regions. ''White pollution'' is still going on. Write a letter to the editor(s) of your local newspaper to: 1) give your opinions briefly, and 2) make two or three suggestions.', 2009, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2010-postgrad-en1', '考研英语一小作文 2010', 'You are supposed to write for the Postgraduates'' Association a notice to recruit volunteers for an international conference on globalization. The notice should include the basic qualifications for applicants and other information which you think is relevant.', 2010, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2011-postgrad-en1', '考研英语一小作文 2011', 'Write a letter to a friend of yours to: 1) recommend one of your favorite movies and 2) give reasons for your recommendation.', 2011, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2012-postgrad-en1', '考研英语一小作文 2012', 'Some international students are coming to your university. Write them an email in the name of the Students'' Union to: 1) extend your welcome and 2) provide some suggestions for their campus life here.', 2012, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2013-postgrad-en1', '考研英语一小作文 2013', 'Write an e-mail of about 100 words to a foreign teacher in your college, inviting him/her to be a judge for the upcoming English speech contest. You should include the details you think necessary.', 2013, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2014-postgrad-en1', '考研英语一小作文 2014', 'Write a letter of about 100 words to the president of your university, suggesting how to improve students'' physical condition. You should include the details you think necessary.', 2014, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2015-postgrad-en1', '考研英语一小作文 2015', 'You are going to host a club reading session. Write an email of about 100 words recommending a book to the club members. You should state reasons for your recommendation.', 2015, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2016-postgrad-en1', '考研英语一小作文 2016', 'Suppose you are a librarian in your university. Write a notice of about 100 words, providing the newly-enrolled international student with relevant information about the library.', 2016, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2017-postgrad-en1', '考研英语一小作文 2017', 'You are to write an email to James Cook, a newly-arrived Australian professor, recommending some tourist attractions in your city. Please give reasons for your recommendation.', 2017, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2018-postgrad-en1', '考研英语一小作文 2018', 'Write an email to all international experts on campus, inviting them to attend the graduation ceremony. In your email, you should include time, place and other relevant information about the ceremony.', 2018, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2019-postgrad-en1', '考研英语一小作文 2019', 'Suppose you are working for the ''Aiding Rural Primary Schools'' project of your university. Write an email to answer the inquiry from an international student volunteer, specifying the details of the project.', 2019, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2020-postgrad-en1', '考研英语一小作文 2020', 'The students union of your university has assigned you to inform the international students about an upcoming singing contest. Write a notice in about 100 words.', 2020, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2021-postgrad-en1', '考研英语一小作文 2021', 'A foreign friend of yours has recently graduated from college and intends to find a job in China. Write him/her an e-mail to make some suggestions.', 2021, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2022-postgrad-en1', '考研英语一小作文 2022', 'Write an email to a professor at a British university, inviting him/her to organize a team for the international innovation contest to be held at your university.', 2022, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2023-postgrad-en1', '考研英语一小作文 2023', 'Write a notice to recruit a student for Prof. Smith''s research project on campus sports activities. Specify the duties and requirements of the job.', 2023, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2024-postgrad-en1', '考研英语一小作文 2024', 'Read the following email from an international student and write a reply. [Paul的邮件：需要做关于古代中国科学家的口头报告，不知道如何准备，请Li Ming给些建议。]', 2024, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2025-postgrad-en1', '考研英语一小作文 2025', 'Read the following email from your classmate Paul and write him a reply. [Paul的邮件：听说Li Ming邀请了年轻工匠在校园展示创新手工艺，想了解详情并希望参与准备工作。]', 2025, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2005-2025）', 1)
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    prompt_text = VALUES(prompt_text),
    image_url = VALUES(image_url),
    image_description = VALUES(image_description),
    material_text = VALUES(material_text),
    task = VALUES(task),
    source = VALUES(source),
    is_active = VALUES(is_active);

-- 英语一 大作文（task2）
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, source, is_active) VALUES
    (4, '2005-postgrad-en1', '考研英语一大作文 2005', 'Write an essay of 160-200 words based on the following drawing. In your essay, you should first describe the drawing, then interpret its meaning, and give your comment on it.', 2005, NULL, '养老"足球赛"。图中有四个孩子（大儿子、二儿子、三儿子、小女儿）各自用足球门框承担着老父亲的身体，隐喻子女推诿养老责任的社会现象。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2006-postgrad-en1', '考研英语一大作文 2006', 'Study the following photos carefully and write an essay in which you should describe the photos briefly, interpret the social phenomenon reflected by them, and give your point of view.', 2006, NULL, '左图：把崇拜写在脸上；右图：花300元做个"小贝头"（Beckham贝克汉姆——英国足球名星）。两张照片展示中国青少年崇拜贝克汉姆的行为：一人将BECKHAM字样写在脸上，另一人花高价做贝克汉姆同款发型，反映盲目崇拜明星的社会现象。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2007-postgrad-en1', '考研英语一大作文 2007', 'Write an essay of 160-200 words based on the following drawing. In your essay, you should: 1) describe the drawing briefly, 2) explain its intended meaning, and then 3) support your view with an example/examples.', 2007, NULL, '（猫做梦踢足球）。一只小猫趴在书上睡觉，梦中幻想自己在踢足球进球得分，寓意脱离实际的空想，或对比现实与理想之间的差距。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2008-postgrad-en1', '考研英语一大作文 2008', 'Write an essay of 160-200 words based on the following drawing. In your essay, you should: 1) describe the drawing briefly, 2) explain its intended meaning, and then 3) give your comments.', 2008, NULL, '你一条腿，我一条腿；你我一起，走南闯北。两人各只有一条腿，但合力用双腿共同支撑，协作前行，寓意合作共赢、互助的重要性。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2009-postgrad-en1', '考研英语一大作文 2009', 'Write an essay of 160-200 words based on the following drawing. In your essay, you should: 1) describe the drawing briefly, 2) explain its intended meaning, and then 3) give your comments.', 2009, NULL, '网络的"近"与"远"。图中一张蜘蛛网形状的图，网上坐满了各种人（玩电脑的、聊天的等），寓意网络让地理上遥远的人变近，却让身边的人变远。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2010-postgrad-en1', '考研英语一大作文 2010', 'Write an essay of 160-200 words based on the following drawing. In your essay, you should: 1) describe the drawing briefly, 2) explain its intended meaning, and 3) give your comments.', 2010, NULL, '文化"火锅"，既美味又营养。一个火锅中装有写着各种文化词汇的食材（佛教、舞蹈、音乐、名著、围棋、京剧等），寓意文化多元融合，兼容并蓄。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2011-postgrad-en1', '考研英语一大作文 2011', 'Write an essay of 160-200 words based on the following drawing. In your essay, you should: 1) describe the drawing briefly, 2) explain its intended meaning, and 3) give your comments.', 2011, NULL, '旅程之"余"。一艘小船在河上行驶，船上坐着一个人，船后方河面漂满了垃圾废物，寓意旅游/发展过程中对环境的破坏。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2012-postgrad-en1', '考研英语一大作文 2012', 'Write an essay of 160-200 words based on the following drawing. In your essay, you should: 1) describe the drawing briefly, 2) explain its intended meaning, and 3) give your comments.', 2012, NULL, '左图人物说：全完了！；右图人物说：幸好还剩点儿。同一件事（桶里的东西洒了大半），两个人态度截然不同：一人绝望，一人乐观，寓意面对挫折心态的重要性。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2013-postgrad-en1', '考研英语一大作文 2013', 'Write an essay of 160-200 words based on the following drawing. In your essay, you should: 1) describe the drawing briefly, 2) interpret its intended meaning, and 3) give your comments.', 2013, NULL, '选择。图中一排毕业生站在高处，面前是一条向上的陡坡，坡上写着：就业、出国、创业、升学等选项，寓意毕业生面临人生道路的多元选择。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2014-postgrad-en1', '考研英语一大作文 2014', 'Write an essay of 160-200 words based on the following drawing. In your essay, you should: 1) describe the drawing briefly, 2) interpret its intended meaning, and 3) give your comments.', 2014, NULL, '相携。对比图：三十年前，高个子妈妈牵着矮小孩子的手；现在，高个子孩子牵着矮小老人（妈妈）的手，寓意亲情传承与反哺，儿女长大后反过来照顾父母。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2015-postgrad-en1', '考研英语一大作文 2015', 'Write an essay of 160-200 words based on the following drawing. In your essay, you should: 1) describe the picture briefly, 2) interpret its intended meaning, and 3) give your comments.', 2015, NULL, '手机时代的聚会。四个人坐在餐桌前聚会，桌上摆满菜肴，但四人全都低头玩手机，无人互动交流，讽刺手机对人际关系的侵蚀。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2016-postgrad-en1', '考研英语一大作文 2016', 'Write an essay of 160-200 words based on the following pictures. In your essay, you should: 1) describe the pictures briefly, 2) interpret the meaning, and 3) give your comments.', 2016, NULL, '与其只提要求，不如做个榜样。左图：父亲指着儿子说"你给我好好学习！"，儿子愁眉苦脸；右图：父亲自己伏案认真工作/学习，儿子也在旁边勤奋学习，寓意以身作则的重要性。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2017-postgrad-en1', '考研英语一大作文 2017', 'Write an essay of 160-200 words based on the following pictures. In your essay, you should: 1) describe the picture briefly, 2) interpret the meaning, and 3) give your comments.', 2017, NULL, '"有书"与"读书"。左图：一人坐在堆满书的书房里，满足地说"我有这么多书！"；右图：一人坐在书桌前认真阅读，说"我争取今年读完20本书。"对比拥有书与真正读书的区别，寓意行动力比占有更重要。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2018-postgrad-en1', '考研英语一大作文 2018', 'Write an essay of 160-200 words based on the picture below. In your essay, you should: 1) describe the picture briefly, 2) interpret the meaning, and 3) give your comments.', 2018, NULL, '选课进行时。一名学生坐在电脑前面对选课系统，左边气泡写着"知识新、重创新、有难度"，右边气泡写着"给分高、易通过、作业少"，揭示大学生选课时重功利轻学习的心态。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2019-postgrad-en1', '考研英语一大作文 2019', 'Write an essay of 160-200 words based on the picture below. In your essay, you should: 1) describe the picture briefly, 2) interpret the implied meaning, and 3) give your comments.', 2019, NULL, '途中。两人爬山途中坐在山坡上休息，一人说"累了，我不爬了。"另一人劝说"别呀！休息一下再接着爬。"寓意坚持与放弃，在追求目标途中遇到困难时需要坚持不懈。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2020-postgrad-en1', '考研英语一大作文 2020', 'Write an essay of 160-200 words based on the pictures below. In your essay, you should: 1) describe the pictures briefly, 2) interpret the implied meaning, and 3) give your comments.', 2020, NULL, '习惯。左图：一名女生伏案工作，气泡说"尽早完成才放心"；右图：一名男生懒散地躺着，气泡说"不到最后不动手"。对比两种截然不同的工作/学习习惯，寓意及时行动的重要性。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2021-postgrad-en1', '考研英语一大作文 2021', 'Write an essay of 160-200 words based on the picture below. In your essay, you should: 1) describe the picture briefly, 2) interpret the implied meaning, and 3) give your comments.', 2021, NULL, '（学戏与兴趣）。小女孩对父亲说："爸爸，很多同学觉得学唱戏不好玩。"父亲回答："你自己不是喜欢吗？那就足够了。"寓意不随波逐流，应坚持自己的兴趣和热爱。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2022-postgrad-en1', '考研英语一大作文 2022', 'Write an essay of 160-200 words based on the picture below. In your essay, you should: 1) describe the picture briefly, 2) interpret the implied meaning, and 3) give your comments.', 2022, NULL, '校园讲座。两名学生站在校园讲座海报前，一人说"不是我们专业的，听了也没多大用。"另一人说"去听肯定有好处。"寓意跨学科学习与开放心态的重要性。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2023-postgrad-en1', '考研英语一大作文 2023', 'Write an essay based on the picture below. In your essay, you should: 1) describe the picture briefly, 2) interpret the implied meaning, and 3) give your comments.', 2023, NULL, '（龙舟赛）。河边龙舟竞渡，岸上观众人山人海，两位老人感叹说："真好啊，咱们村的龙舟赛越来越热闹了！"寓意传统文化的传承与复兴，民俗活动焕发生机。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2024-postgrad-en1', '考研英语一大作文 2024', 'Write an essay based on the picture and the chart below. In your essay, you should: 1) describe the picture and the chart briefly, 2) interpret the implied meaning, and 3) give your comments.', 2024, NULL, '市民健身区 + 某市近三年公园数量（单位：座）。左图：市民在新建的小公园里跑步健身，人物说"家门口新建的小公园，真不错！"；右图：柱状图显示某市公园数量逐年增加：2020年406座、2021年532座、2022年670座。寓意城市绿色基础设施建设的发展成果惠及市民。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1),
    (4, '2025-postgrad-en1', '考研英语一大作文 2025', 'Write an essay of 160-200 words based on the following table. In your essay, you should: 1) describe the table briefly, 2) explain its intended meaning, and 3) give your comments.', 2025, NULL, '近年来全国居民平均每百户年末主要耐用消费品拥有量。表格数据：2014/2017/2020/2023年，全国居民每百户空调（75.2→96.1→117.7→145.9台）、洗衣机（83.7→91.7→96.7→98.2台）、电冰箱（85.5→95.3→101.8→103.4台）拥有量逐年增长，反映居民生活水平持续提升。', NULL, 'task2', '考研英语作文真题合集（2005-2025）', 1)
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    prompt_text = VALUES(prompt_text),
    image_url = VALUES(image_url),
    image_description = VALUES(image_description),
    material_text = VALUES(material_text),
    task = VALUES(task),
    source = VALUES(source),
    is_active = VALUES(is_active);

-- 英语二 小作文（task1）
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, source, is_active) VALUES
    (4, '2010-postgrad-en2', '考研英语二小作文 2010', 'You have just come back from the U.S. as a member of a Sino-American cultural exchange program. Write a letter to your American colleague to: 1) express your thanks for his/her warm reception; 2) welcome him/her to visit China in due course.', 2010, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2011-postgrad-en2', '考研英语二小作文 2011', 'Suppose your cousin Li Ming has just been admitted to a university. Write him/her a letter to: 1) congratulate him/her, and 2) give him/her suggestions on how to get prepared for university life.', 2011, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2012-postgrad-en2', '考研英语二小作文 2012', 'Suppose you have found something wrong with the electronic dictionary that you bought from an online store the other day. Write an email to the customer service center to: 1) make a complaint, and 2) demand a prompt solution.', 2012, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2013-postgrad-en2', '考研英语二小作文 2013', 'Suppose your class is to hold a charity sale for kids in need of help. Write your classmates an email to: 1) inform them about the details, and 2) encourage them to participate.', 2013, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2014-postgrad-en2', '考研英语二小作文 2014', 'Suppose you are going to study abroad and share an apartment with John, a local student. Write him an email to: 1) tell him about your living habits, and 2) ask for advice about living there.', 2014, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2015-postgrad-en2', '考研英语二小作文 2015', 'Suppose your university is going to host a summer camp for high school students. Write a notice to: 1) briefly introduce the camp activities, and 2) call for volunteers.', 2015, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2016-postgrad-en2', '考研英语二小作文 2016', 'Suppose you won a translation contest and your friend, Jack, wrote an email to congratulate you and ask for advice on translation. Write him a reply to: 1) thank him, and 2) give your advice.', 2016, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2017-postgrad-en2', '考研英语二小作文 2017', 'Suppose you are invited by Professor Williams to give a presentation about Chinese culture to a group of international students. Write a reply to: 1) accept the invitation, and 2) introduce the key points of your presentation.', 2017, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2018-postgrad-en2', '考研英语二小作文 2018', 'Suppose you have to cancel your travel plan and will not be able to visit Professor Smith. Write him an email to: 1) apologize and explain the situation, and 2) suggest a future meeting.', 2018, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2019-postgrad-en2', '考研英语二小作文 2019', 'Suppose Professor Smith asked you to plan a debate on the theme of city traffic. Write him an email to: 1) suggest a specific topic with your reasons, and 2) tell him about your arrangements.', 2019, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2020-postgrad-en2', '考研英语二小作文 2020', 'Suppose you are planning a tour of a historical site for a group of international students. Write them an email to: 1) tell them about the site, and 2) give them some tips for the tour.', 2020, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2021-postgrad-en2', '考研英语二小作文 2021', 'Suppose you are organizing an online meeting. Write an e-mail to Jack, an international student, to: 1) invite him to participate, and 2) tell him the details.', 2021, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2022-postgrad-en2', '考研英语二小作文 2022', 'Suppose you are planning a campus food festival. Write an e-mail to the international students in your university to: 1) introduce the food festival, and 2) invite them to participate.', 2022, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2023-postgrad-en2', '考研英语二小作文 2023', 'An art exhibition and a robot show are to be held on Sunday, and your friend David asks you which one he should go to. Write him an email to: 1) make a suggestion, and 2) give your reason(s).', 2023, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2024-postgrad-en2', '考研英语二小作文 2024', 'Suppose you and Jack are going to do a survey on the protection of old houses in an ancient town. Write him an email to: 1) put forward your plan, and 2) ask for his opinion.', 2024, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2025-postgrad-en2', '考研英语二小作文 2025', 'Suppose you are planning a short play based on a classic Chinese novel. Write your friend John an email to: 1) introduce the play, and 2) invite him to take part in it.', 2025, NULL, NULL, NULL, 'task1', '考研英语作文真题合集（2010-2025）', 1)
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    prompt_text = VALUES(prompt_text),
    image_url = VALUES(image_url),
    image_description = VALUES(image_description),
    material_text = VALUES(material_text),
    task = VALUES(task),
    source = VALUES(source),
    is_active = VALUES(is_active);

-- 英语二 大作文（task2）
INSERT INTO essay_prompt (stage_id, paper, title, prompt_text, exam_year, image_url, image_description, material_text, task, source, is_active) VALUES
    (4, '2010-postgrad-en2', '考研英语二大作文 2010', 'In this part, you are asked to write an essay based on the following chart. In your writing, you should: 1) interpret the chart and 2) give your comments.', 2010, NULL, 'Mobile-phone subscriptions (2000-2008)。折线图展示2000-2008年间发展中国家与发达国家手机订阅数量变化。发展中国家手机用户从约5亿猛增至约35亿，远超发达国家（约10亿），显示发展中国家移动通信的爆炸性增长。', NULL, 'task2', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2011-postgrad-en2', '考研英语二大作文 2011', 'Write an essay based on the following chart. In your writing, you should: 1) interpret the chart, and 2) give your comments.', 2011, NULL, '2008、2009年国内轿车市场部分品牌市场份额示意图。柱状图对比2008年和2009年国内轿车市场中国产品牌（约25%→30%）、日系品牌（约35%→30%）、美系品牌（约10%→10%）的市场份额变化，显示国产品牌增长、日系略降。', NULL, 'task2', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2012-postgrad-en2', '考研英语二大作文 2012', 'Write an essay based on the following table. In your writing, you should: 1) describe the table, and 2) give your comments.', 2012, NULL, '某公司员工工作满意度调查。表格按年龄段（≤40岁、41-50岁、>50岁）统计员工满意度：≤40岁满意16.7%、不清楚50%、不满意33.3%；41-50岁满意0%、不清楚36%、不满意64%；>50岁满意40%、不清楚50%、不满意10%。中年群体满意度最低。', NULL, 'task2', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2013-postgrad-en2', '考研英语二大作文 2013', 'Write an essay based on the following chart. In your writing, you should: 1) interpret the chart, and 2) give your comments.', 2013, NULL, '某高校学生兼职情况。柱状图显示某高校大一至大四学生兼职比例逐年上升：大一67.77%、大二71.13%、大三71.93%、大四88.24%，反映在校大学生参与兼职的普遍性及年级越高越普遍的趋势。', NULL, 'task2', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2014-postgrad-en2', '考研英语二大作文 2014', 'Write an essay based on the following chart. In your essay, you should: 1) interpret the chart and 2) give your comments.', 2014, NULL, '20年间中国城镇人口、乡村人口变化图（单位：百万）。柱状图对比1990、2000、2010年城镇与乡村人口：1990年城镇约300M、乡村约800M；2000年城镇约450M、乡村约800M；2010年城镇约660M、乡村约660M。城镇化进程明显加速，城乡人口趋于持平。', NULL, 'task2', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2015-postgrad-en2', '考研英语二大作文 2015', 'Write an essay based on the following chart. In your writing, you should: 1) interpret the chart, and 2) give your comment.', 2015, NULL, '我国某市居民春节假期花销比例。饼图显示某市居民春节花销分布：新年礼物40%、聚会吃饭20%、交通20%、其他20%，新年礼物支出占比最大，反映节日消费结构特点。', NULL, 'task2', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2016-postgrad-en2', '考研英语二大作文 2016', 'Write an essay based on the following chart. In your writing, you should: 1) interpret the chart, and 2) give your comments.', 2016, NULL, '某高校学生旅游目的调查。饼图显示学生旅游目的：欣赏风景37%、缓解压力33%、广交朋友9%、培养独立能力6%、其他15%。欣赏风景与减压是最主要动机。', NULL, 'task2', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2017-postgrad-en2', '考研英语二大作文 2017', 'Write an essay based on the chart below. In your essay, you should: 1) interpret the chart, and 2) give your comments.', 2017, NULL, '2013—2015我国博物馆数量和参观人数。折线图显示2013-2015年博物馆数量（4165→4510→4692家）和参观人次（6378→7177→7811十万人次）均呈上升趋势，两条线同步增长，反映文化事业繁荣发展。', NULL, 'task2', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2018-postgrad-en2', '考研英语二大作文 2018', 'Write an essay based on the chart below. In your writing, you should: 1) interpret the chart, and 2) give your comments.', 2018, NULL, '2017年某市消费者选择餐厅时的关注因素。饼图显示消费者选餐厅考量因素：特色36.3%、服务27.4%、环境24.3%、价格7.3%、其他4.7%。餐厅特色是最主要考量，价格反而排名靠后，反映消费升级趋势。', NULL, 'task2', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2019-postgrad-en2', '考研英语二大作文 2019', 'Write an essay based on the chart below. In your writing, you should: 1) interpret the chart, and 2) give your comments.', 2019, NULL, '某高校2013年和2018年本科毕业生去向统计。对比柱状图：就业比例从68.1%降至60.7%；升学比例从26.3%升至34%；创业比例从1.3%升至2.6%。说明近年来应届生升学意愿增强，就业选择比例有所下降。', NULL, 'task2', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2020-postgrad-en2', '考研英语二大作文 2020', 'Write an essay based on the following chart. In your writing, you should: 1) interpret the chart, and 2) give your comments.', 2020, NULL, '某高校学生手机阅读目的调查。饼图显示学生手机阅读目的：学习知识59.5%、消磨时间21.3%、获取信息17%、其他2.2%。超过半数学生以获取知识为主要目的，体现积极学习态度。', NULL, 'task2', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2021-postgrad-en2', '考研英语二大作文 2021', 'Write an essay based on the chart below. In your writing, you should: 1) interpret the chart, and 2) give your comments.', 2021, NULL, '某市居民锻炼方式调查。柱状图显示居民锻炼方式偏好：独自锻炼54.3%、和朋友一起47.7%、和家人一起23.9%、团体活动15.8%。独自锻炼占主流，社交性锻炼也相当普遍。', NULL, 'task2', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2022-postgrad-en2', '考研英语二大作文 2022', 'Write an essay based on the following chart. In your writing, you should: 1) interpret the chart, and 2) give your comments.', 2022, NULL, '2018—2020年我国快递业务量变动情况（单位：十亿件）。分组柱状图显示快递总体业务量（51→64→83十亿件）和农村业务量（12→15→30十亿件）均大幅增长，农村快递增速尤为突出（2020年翻倍），反映农村电商的快速崛起。', NULL, 'task2', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2023-postgrad-en2', '考研英语二大作文 2023', 'Write an essay based on the chart below. In your essay, you should: 1) describe and interpret the chart, and 2) give your comments.', 2023, NULL, '2012—2021年我国居民健康素养水平。折线图显示我国居民健康素养水平从2012年8.80%持续上升至2021年25.40%，近十年增长约3倍，特别是2016年后增速加快，反映健康教育事业取得显著成效。注：健康素养水平指具备基本健康素养的人在总人群(15-69岁城乡居民)中所占比例。', NULL, 'task2', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2024-postgrad-en2', '考研英语二大作文 2024', 'Write an essay based on the chart below. In your essay, you should: describe and interpret the chart, and give your comments.', 2024, NULL, '某高校劳动实践课学生主要收获调查。横向条形图显示学生在劳动实践课的主要收获：学习了相关知识91.3%、提升了动手能力84.8%、感觉到心情舒畅54.4%、增强了合作能力32.6%。知识与动手能力收获最为突出。', NULL, 'task2', '考研英语作文真题合集（2010-2025）', 1),
    (4, '2025-postgrad-en2', '考研英语二大作文 2025', 'Write an essay based on the chart below. In your essay, you should: 1) describe and interpret the chart, and 2) give your comments.', 2025, NULL, '某社区老年人主要日常休闲活动调查。柱状图显示老年人休闲活动偏好：看电视90.8%、散步68.3%、养花34.7%、阅读31.8%、下棋18.4%。看电视是最主要活动，散步位居第二，体现老年人偏好低强度休闲活动的特点。', NULL, 'task2', '考研英语作文真题合集（2010-2025）', 1)
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    prompt_text = VALUES(prompt_text),
    image_url = VALUES(image_url),
    image_description = VALUES(image_description),
    material_text = VALUES(material_text),
    task = VALUES(task),
    source = VALUES(source),
    is_active = VALUES(is_active);
